name: dartvcr
description: A Dart library for recording and replaying HTTP requests. Port of EasyVCR.
version: 0.2.0
repository: https://github.com/nwithan8/dartvcr

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  json_annotation: ^4.7.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  collection: ^1.15.0
  dependency_validator:
  json_serializable: ^6.0.0
  lints: ^2.0.0
  mockito: ^5.0.0
  pub_semver:
  test: ^1.16.0
  yaml: ^3.0.0
  yaml_edit:
